baseURL: "https://nordicflowacroyoga.fi"
languageCode: "fi-fi"
title: "Nordic Flow Acroyoga"
params:
  logo: /img/logo-trans.png
  email: nordicflowacroyoga@gmail.com
  instagram: nordicflowacroyoga
  facebook: nordicflowacroyoga
  phone: +358 40 0343418
  keywords: nordic flow acroyoga,nordic flow,acroyoga,yoga
  description: Nordic Flow Acroyoga
  shopUrl: https://holvi.com/shop/akrojoogataanyhdessa/

DefaultContentLanguage: fi
disableLanguages: ["en"]
languages:
  fi:
    params:
      home: Etusivu
      signin: Ilmoittaudu
      shop: Kauppa

  en:
    params:
      home: Home
      signin: Signin
      shop: Shop
