baseURL: "https://preview.nordicflowacroyoga.fi"
languageCode: "fi-fi"
title: "Nordic Flow Acroyoga"
params:
  logo: /img/logo-trans.png
  email: nordicflowacroyoga@gmail.com
  instagram: nordicflowacroyoga
  facebook: nordicflowacroyoga
  phone: +358 .. ......
  keywords: nordic flow acroyoga,nordic flow,acroyoga,yoga
  description: Nordic Flow Acroyoga

DefaultContentLanguage: fi
languages:
  fi:
    params:
      home: Etusivu

  en:
    params:
      home: Home
